# Generated by Django 3.2.11 on 2022-01-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving_api', '0002_file_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
