# Generated by Django 3.2.11 on 2022-01-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_address', models.TextField()),
                ('earnings', models.FloatField()),
                ('storage_mb', models.FloatField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
