# Generated by Django 3.2.11 on 2022-01-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='storage_mb',
            new_name='utilised_storage_mb',
        ),
    ]
